### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by raj5036**

### CODE REVIEW

**Comment by raj5036** [comment]
Removed the JSX option and one other unnecessary parserOption from the file .

**Comment by raj5036** [comment]
I have changed some parts of  the authcontroller.js file .The user can now validate themselves by both their username or email. Please review the changes .

**Comment by elit-altum** [comment]
@raj5036 Have you tested this route via Postman ?

**Comment by raj5036** [comment]
Sorry I should've done that, my bad. Ok I will be checking it and then inform you.

**Comment by elit-altum** [comment]
Please update the PR by complying with [these guidelines](https://github.com/elit-altum/AuthExp-Express-Starter/blob/master/CONTRIBUTING.md)
Always read the ```CONTRIBUTING.md``` of any repo before contributing to it.

**Comment by raj5036** [comment]
Okay.. I will remember that.

**Pull request closed without merging**
